### PR TITLE
Auto pull request

### PR DESCRIPTION
**Pull request by ScottTrenda**
Tries to get the pull request from the current branch if not specified.

### CODE REVIEW

**Comment by bbergstrom** [comment]
CR :+1:

I plan to do QA and cut a new release next week.

**Comment by bbergstrom** [comment]
The pull request search was bugged as it didn't filter to the branch correctly.  I had to switch it to the query api call to filter accurately.

Still need to update tests.

**Comment by bbergstrom** [comment]
@ScottTrenda @anfleene @ChrisArcand Will you give my final patches here some CR.

**Comment by bbergstrom** [comment]
:octocat: Merged into staging.2014.07.28.

**Comment by bbergstrom** [comment]
QA now passes for me.
```
brianbergstrom@bb-mbp octopolo (auto-pull-request)$ op stage-up
Pull request for current branch is number 70
git checkout staging.2014.07.28
...
```

**Comment by ChrisArcand** [comment]
Code on the last two commits looks legit to me :+1:

**Comment by bbergstrom** [comment]
:octocat: Merged into staging.2014.07.28.

**Comment by ScottTrenda** [comment]
CR :+1:

**Comment by ChrisArcand** [comment]
You stage up that gem PR, @bbergstrom :fist:

**Pull request merged**
