### PR TITLE
Cannot yet think of a better way to do this

### PR DESCRIPTION
**Pull request by pete2786**

### CODE REVIEW

**Comment by NickLaMuro** [comment]
Also, forgot to mention, `Open3.capture` does support passing in individual env args to a command:

https://ruby-doc.org/stdlib-2.2.0/libdoc/open3/rdoc/Open3.html#method-c-capture3

And just follows the `Process.spawn`/`Kernel.spawn` conventions for command args:

https://ruby-doc.org/core-2.2.0/Process.html#method-c-spawn

**Comment by pete2786** [comment]
Nice, thanks for the feedback.

**Comment by NickLaMuro** [comment]
> Nice, thanks for the feedback.

Well, your PR title did kind of ask for it 😏

**Comment by pete2786** [comment]
Closing for now, will come back with a solution similar to what @NickLaMuro proposed if `overcommit` catches on.

**Pull request closed without merging**
